services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: education-certification-system
    environment:
      SPRING_PROFILES_ACTIVE: docker
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - rabbitmq_net
    ports:
      - "18080:8080"
    restart: unless-stopped

networks:
  rabbitmq_net:
    external: true
    name: rabbitmq_default
