spring:
  docker:
    compose:
      enabled: false
  profiles:
    active: dev
  rabbitmq:
    port: 5672
    username: admin
    password: 123456
    virtual-host: /
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0
    validate-on-migrate: true
    clean-disabled: true

mybatis-plus:
  mapper-locations: classpath*:com/educationcertificationsystem/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
